[profile.default]
solc_version = "0.7.6"
optimizer = true
optimizer_runs = 2000000
via_ir = false
auto_detect_solc = false
[fmt]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
   { access = "write", path = "./output/incentiveId.txt"},
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
